# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors поки не підтримує Україну — лишено на майбутнє
github: [RiasJ1Dar]

custom: ["https://send.monobank.ua/jar/4XsDm8vmF2"]
