# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [RiasJ1Dar]

# Розкоментуй потрібне і впиши свій логін:
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
# liberapay: username
# custom: ["https://paypal.me/username"]
